import { useEffect, useState, type ReactNode } from "react";
import { useStore } from "../lib/store-context";
import { nyId } from "../lib/format";
import type { AppState, Kapittel } from "../lib/types";
import type { Hendelse, KapittelVedlegg } from "../lib/hendelser";
import { EKSAMEN, foldForsok, foldOkter, framgang, gjeldendeNotat, innholdIFag, innholdSchema, notatHistorikk, oppgaver, osloDato, stabileId, startmelding, synligVurdering, underpunkter, type Arbeidsmate, type Forsok, type Hjelp, type Innhold, type Okt, type Oppgave } from "../lib/laering";
import { ovingKo } from "../lib/oving-ko";
import { lastOppVedlegg, vedleggUrl } from "../lib/vedlegg-klient";
import { FagordListe } from "./Fagord";
import { Prover } from "./Prover";
import { Utvikling } from "./Utvikling";

const felt = "mt-1 w-full rounded-lg border border-[#191C1F]/20 bg-white px-3 py-2 text-sm";
const knapp = "rounded-lg bg-[#191C1F] px-3 py-2 text-sm text-white disabled:opacity-40";
const sekundar = "rounded-lg bg-[#ECEBE5] px-3 py-2 text-sm disabled:opacity-40";
const etikett = "block text-sm font-medium";
const MODUS: Record<Arbeidsmate, string> = { laering: "Læring", selvtest: "Selvtest", eksamen: "Eksamenstrening" };
const HJELP: Record<Hjelp, string> = { ingen: "Uten hjelp", hint: "Med hint", "vist-losning": "Løsningen var vist", ukjent: "Hjelp ikke registrert" };
function Kort({ children }: { children: ReactNode }) { return <section className="space-y-3 rounded-2xl bg-white p-4 sm:p-5">{children}</section>; }
function useJobb() {
  const [feil, setFeil] = useState(""); const [venter, setVenter] = useState(false);
  async function jobb(fn: () => Promise<void>) { setFeil(""); setVenter(true); try { await fn(); return true; } catch (e) { setFeil(e instanceof Error ? e.message : String(e)); return false; } finally { setVenter(false); } }
  return { jobb, venter, feil: feil ? <p role="alert" className="text-sm text-red-800">{feil}</p> : null };
}
function base(id: string, fagId: string) { return { id, fagId, tid: new Date().toISOString(), kilde: "selv" as const }; }
export function KopierAi({ okt }: { okt: Okt }) {
  const [vis, setVis] = useState(false); const [kopiert, setKopiert] = useState(false);
  async function kopier() { setVis(true); try { await navigator.clipboard.writeText(startmelding(okt)); setKopiert(true); } catch { setKopiert(false); } }
  return <div><button className={knapp} onClick={() => void kopier()}>Øv med AI</button>{vis && <div className="mt-3 space-y-2"><p className="text-sm">{kopiert ? "Startmeldingen er kopiert. " : "Kopier startmeldingen. "}Lim den inn i AI-chatten med MCP tilkoblet.</p><textarea aria-label="Startmelding til AI" className={felt} readOnly value={startmelding(okt)} rows={4}/></div>}</div>;
}
export function BokRom() {
  const { state, setInnstillinger, setFagordStatus } = useStore(); const fagId = state.innstillinger.aktivtFag;
  const kapitler = state.kapitler.filter(k => k.fagId === fagId).sort((a,b) => a.nummer-b.nummer);
  const lagret = state.innstillinger.bokValg?.[fagId];
  const k = kapitler.find(k => k.id === lagret?.kapittelId) ?? kapitler[0]; const plass = lagret?.plass ?? "kapittel";
  const [importer, setImporter] = useState(false);
  const [nyttKapittel, setNyttKapittel] = useState(false);
  function velg(kapittelId: string, plass: string) { setInnstillinger({ bokValg: { ...state.innstillinger.bokValg, [fagId]: { kapittelId, plass } } }); }
  const opp = k ? oppgaver(state, k.id) : [];
  return <div className="space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-[#191C1F]/60">Bokas rekkefølge · egne notater · øving med tilbakemelding</p><button className={sekundar} onClick={() => { setNyttKapittel(false); setImporter(!importer); }}>{importer ? "Lukk innlegging" : "Legg inn bokinnhold"}</button><button className={sekundar} onClick={() => { setNyttKapittel(true); setImporter(true); }}>Nytt kapittel</button></div>
    {(importer || !k) && <InnholdImport key={nyttKapittel ? `nytt-${fagId}` : k?.id ?? fagId} kapittel={nyttKapittel ? undefined : k} onFerdig={id => { setImporter(false); setNyttKapittel(false); velg(id, "kapittel"); }} />}
    {k && <div className="grid gap-4 md:grid-cols-[250px_minmax(0,1fr)]">
      <nav className="space-y-1 rounded-2xl bg-white p-3 md:sticky md:top-44 md:max-h-[72vh] md:overflow-y-auto md:self-start" aria-label="Bok og underpunkter">
        {kapitler.map(kap => <div key={kap.id}><button className={`w-full rounded-lg px-2 py-2 text-left text-sm ${kap.id === k.id ? "bg-[#ECEBE5] font-medium" : ""}`} onClick={() => velg(kap.id,"kapittel")}>{kap.nummer}. {kap.navn}</button>
          {kap.id === k.id && <div className="ml-2 border-l border-black/10 pl-2">{[{id:"kapittel",navn:"Kapittelnotat"},...underpunkter(kap),{id:"bok-oppsummering",navn:"Bokas oppsummering"},{id:"min-oppsummering",navn:"Min oppsummering"},{id:"oppgaver",navn:"Kontrollspørsmål og oppgaver"},{id:"hull",navn:"Dette må jeg øve på"},{id:"ordbank",navn:"Ordbank"},{id:"vedlegg",navn:"Foto og PDF"}].map(s => <button key={s.id} className={`block w-full rounded px-2 py-1.5 text-left text-xs ${plass === s.id ? "bg-[#E6EFE8] font-medium" : "text-black/65"}`} onClick={() => velg(kap.id,s.id)}>{s.navn}</button>)}</div>}
        </div>)}
      </nav>
      <div className="min-w-0 space-y-4"><header><p className="text-xs text-black/50">{k.bokTittel ?? "Læreverket"}{k.utgave ? ` · ${k.utgave}` : ""}{k.sider ? ` · s. ${k.sider.fra}–${k.sider.til}` : ""}</p><h2 className="mt-1 text-xl font-medium">{k.nummer}. {k.navn}</h2></header>
        {plass === "oppgaver" ? <><OktStart kapittel={k}/>{(["kontroll","oppgave"] as const).map(type => <section key={type} className="space-y-3"><h3 className="font-medium">{type === "kontroll" ? "Kontrollspørsmål" : "Oppgaver"}</h3>{opp.filter(o => o.type === type).map(o => <OppgaveKort key={o.id} oppgave={o}/>)}{!opp.some(o => o.type === type) && <p className="text-sm text-black/55">Ingen lagt inn ennå. Bruk «Legg inn bokinnhold».</p>}</section>)}</>
        : plass === "bok-oppsummering" ? <BokOppsummering state={state} kapittel={k}/>
        : plass === "hull" ? <Hull kapittel={k}/>
        : plass === "ordbank" ? <FagordListe state={state} temaIds={k.temaIds} onStatus={(id,status) => void setFagordStatus(id,status).catch(() => undefined)}/>
        : plass === "vedlegg" ? <Vedlegg kapittel={k}/>
        : <NotatEditor key={`${k.id}:${plass}`} kapittel={k} plass={plass}/>}
        <TemaKoblinger kapittel={k}/>
      </div>
    </div>}
  </div>;
}
function BokOppsummering({ state, kapittel }: { state: AppState; kapittel: Kapittel }) {
  const s = innholdIFag(state, kapittel.fagId).filter(h => h.innhold.kapittel.id === kapittel.id && h.innhold.oppsummering).at(-1)?.innhold.oppsummering;
  return <Kort><h3 className="font-medium">Bokas oppsummering</h3>{s ? <><p className="whitespace-pre-wrap text-sm leading-relaxed">{s.tekst}</p><Kilde refData={s.referanse}/></> : <p className="text-sm text-black/60">Legg inn oppsummeringen fra boka via «Legg inn bokinnhold» eller AI-chatten.</p>}</Kort>;
}
function Kilde({ refData }: { refData?: { tittel: string; side?: number; original: string; usikker: boolean } }) {
  return refData ? <p className="text-xs text-black/60">Kilde: {refData.tittel}{refData.side ? ` · s. ${refData.side}` : ""} · {refData.original === "arkivert" ? "Original arkivert" : "Originalfil ikke arkivert"}{refData.usikker ? " · Usikker transkripsjon – kontroller originalen" : ""}</p> : null;
}
function NotatEditor({ kapittel, plass }: { kapittel: Kapittel; plass: string }) {
  const { state, appendHendelser } = useStore(); const gjeldende = gjeldendeNotat(state,kapittel.id,plass);
  const [tekst,setTekst] = useState(gjeldende?.tekst ?? ""); const [forelder,setForelder] = useState(gjeldende?.notatId ?? null);
  const [notatId,setId] = useState(() => nyId("notat")); const [lagret,setLagret] = useState(false); const { jobb, feil, venter } = useJobb();
  const historikk = notatHistorikk(state,kapittel.id,plass); const avvik = forelder !== (gjeldende?.notatId ?? null);
  const kommentarer = state.hendelser.filter(h => h.type === "notat-kommentar" && h.kapittelId === kapittel.id && historikk.some(n => n.notatId === h.notatId));
  async function lagre() { const ok = await jobb(async () => appendHendelser([{ ...base(`notat:${notatId}`,kapittel.fagId),type:"notat-versjon",notat:{notatId,kapittelId:kapittel.id,plass,tekst,forelder} }])); if(ok){setForelder(notatId);setId(nyId("notat"));setLagret(true);} }
  return <Kort><h3 className="font-medium">{plass === "min-oppsummering" ? "Min oppsummering" : underpunkter(kapittel).find(s=>s.id===plass)?.navn ?? "Kapittelnotat"}</h3><p className="text-sm text-black/60">Forklar med egne ord. AI-tilbakemeldinger vises separat.</p>
    {avvik && <div role="alert" className="space-y-2 rounded-lg bg-amber-50 p-3 text-sm"><p>Notatet er endret et annet sted. Din tekst er beholdt. Sammenlign med den nye versjonen:</p><pre className="whitespace-pre-wrap font-sans">{gjeldende?.tekst}</pre><button className={sekundar} onClick={()=>{setForelder(gjeldende?.notatId??null);setLagret(false);}}>Jeg har sammenlignet – lagre min tekst som neste versjon</button></div>}
    <textarea aria-label="Egne notater" className={`${felt} min-h-64`} value={tekst} onChange={e=>{setTekst(e.target.value);setLagret(false);}}/>
    <button className={knapp} disabled={venter||avvik} onClick={()=>void lagre()}>{venter?"Lagrer…":"Lagre notat"}</button>{lagret&&<p role="status" className="text-sm text-green-800">Lagret</p>}{feil}
    {historikk.length>0&&<details><summary className="cursor-pointer text-sm">Tidligere versjoner ({historikk.length})</summary>{historikk.slice().reverse().map(n=><div key={n.notatId} className="mt-3 border-t pt-2"><p className="text-xs text-black/55">{n.tid}{n.konflikt?" · Versjonskonflikt – tekst bevart":""}</p><p className="whitespace-pre-wrap text-sm">{n.tekst}</p></div>)}</details>}
    {kommentarer.length>0&&<div className="space-y-2 border-t pt-3"><h4 className="text-sm font-medium">Tilbakemelding på notatene</h4>{kommentarer.map(h=>h.type==="notat-kommentar"&&<p key={h.id} className="whitespace-pre-wrap text-sm">{h.tekst}</p>)}</div>}
  </Kort>;
}
function InnholdImport({ kapittel, onFerdig }: { kapittel?: Kapittel; onFerdig:(id:string)=>void }) {
  const { state,appendHendelser }=useStore();const fagId=state.innstillinger.aktivtFag;
  const [nummer,setNummer]=useState(kapittel?.nummer??(Math.max(0,...state.kapitler.filter(k=>k.fagId===fagId).map(k=>k.nummer))+1));const [navn,setNavn]=useState(kapittel?.navn??"");const [bok,setBok]=useState(kapittel?.bokTittel??"");const [punkter,setPunkter]=useState(kapittel?underpunkter(kapittel).map(s=>s.navn).join("\n"):"");
  const [temaTekst,setTemaTekst]=useState("");const [oppsummering,setOppsummering]=useState("");const [sporsmal,setSporsmal]=useState("");const [type,setType]=useState<"kontroll"|"oppgave">("kontroll");const [side,setSide]=useState("");const [usikker,setUsikker]=useState(false);
  const [originalId,setOriginalId]=useState("");
  const [preview,setPreview]=useState<Innhold|null>(null);const {jobb,feil,venter}=useJobb();
  async function forhandsvis() { await jobb(async()=>{
    const kid=kapittel?.id??`${fagId}-k${String(nummer).padStart(2,"0")}`;
    const ref={tittel:bok.trim()||kapittel?.bokTittel||"Læreverket",...(side?{side:Number(side)}:{}),original:originalId?"arkivert" as const:"ikke-arkivert" as const,...(originalId?{vedleggId:originalId}:{}),usikker};
    const deler=sporsmal.trim()?sporsmal.trim().split(/\n(?=\s*\d+(?:\.\d+)*[.)]?\s)/).filter(Boolean):[];
    const struktur={id:kid,bokId:kapittel?.bokId??`${fagId}-bok`,bokTittel:ref.tittel,nummer,navn,del:kapittel?.del,sider:kapittel?.sider,underpunkter:punkter.split("\n").map(s=>s.trim()).filter(Boolean).map((navn,i)=>({id:kapittel?underpunkter(kapittel).find(s=>s.navn===navn)?.id??underpunkter(kapittel)[i]?.id??`${kid}-u-${stabileId(navn)}`:`${kid}-s${String(i+1).padStart(2,"0")}`,navn}))};
    const inn={importId:"preview",fagId,kapittel:struktur,temaer:temaTekst.split("\n").map(t=>t.trim()).filter(Boolean).map(navn=>({id:`${fagId}-t-${stabileId(navn)}`,navn,maalIds:[],bekreftet:false})),...(oppsummering.trim()?{oppsummering:{tekst:oppsummering,referanse:ref}}:{}),oppgaver:deler.map((d,i)=>{const m=d.match(/^\s*(\d+(?:\.\d+)*[.)]?)\s+([\s\S]*)$/);const tekst=m?.[2]??d;return {id:`${kid}-o-${stabileId(d)}`,tekst,nummer:m?.[1]??String(i+1),type,temaIds:[],maalIds:[],koblingBekreftet:false,referanse:ref,opphav:"bok" as const};})};
    setPreview(innholdSchema.parse(inn));
  }); }
  async function lagre() { if(!preview)return;const inn={...preview,importId:stabileId(JSON.stringify({...preview,importId:""}))};const ok=await jobb(async()=>appendHendelser([{...base(`import:${inn.importId}`,fagId),type:"innhold-importert",innhold:inn}]));if(ok){setPreview(null);setOppsummering("");setSporsmal("");onFerdig(inn.kapittel.id);} }
  return <Kort><h3 className="font-medium">Legg inn bokinnhold</h3><p className="text-sm text-black/60">Foto og PDF kan leses i AI-chatten. Be AI-en lagre innholdet og bevare ordlyd, oppgavenummer og sidetall.</p>
    {!preview?<><div className="grid gap-3 sm:grid-cols-2"><label className={etikett}>Boktittel<input className={felt} value={bok} onChange={e=>setBok(e.target.value)} placeholder="Navn på læreverket"/></label><label className={etikett}>Kapittelnummer<input type="number" min="1" className={felt} value={nummer} onChange={e=>setNummer(Number(e.target.value))}/></label></div><label className={etikett}>Kapitteltittel<input className={felt} value={navn} onChange={e=>setNavn(e.target.value)}/></label>
      <details><summary className="text-sm">Underpunkter og temaer</summary><label className={etikett}>Underpunkter – ett per linje<textarea className={felt} rows={5} value={punkter} onChange={e=>setPunkter(e.target.value)}/></label><label className={etikett}>Nye faglige temaer – ett per linje<textarea className={felt} value={temaTekst} onChange={e=>setTemaTekst(e.target.value)}/></label></details>
      <label className={etikett}>Bokas oppsummering<textarea className={felt} rows={5} value={oppsummering} onChange={e=>setOppsummering(e.target.value)}/></label>
      <label className={etikett}>Spørsmål eller oppgaver<select className={felt} value={type} onChange={e=>setType(e.target.value as typeof type)}><option value="kontroll">Kontrollspørsmål</option><option value="oppgave">Oppgaver</option></select><textarea className={felt} rows={6} value={sporsmal} onChange={e=>setSporsmal(e.target.value)} placeholder={'1. Første spørsmål\n2. Neste spørsmål'}/></label>
      <label className={etikett}>Originalvedlegg<select className={felt} value={originalId} onChange={e=>setOriginalId(e.target.value)}><option value="">Originalfil ikke arkivert</option>{state.hendelser.filter((h):h is KapittelVedlegg=>h.type==="kapittel-vedlegg"&&h.fagId===fagId).map(v=><option key={v.vedleggId} value={v.vedleggId}>{v.filnavn}</option>)}</select></label><label className={etikett}>Side i boka<input type="number" min="1" className={felt} value={side} onChange={e=>setSide(e.target.value)}/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={usikker} onChange={e=>setUsikker(e.target.checked)}/>Transkripsjonen må kontrolleres mot originalen</label><button className={knapp} onClick={()=>void forhandsvis()}>Forhåndsvis og rediger</button></>
    : <><p className="text-sm">{preview.kapittel.navn} · {preview.oppgaver.length} spørsmål · {preview.kapittel.underpunkter.length} underpunkter</p>{preview.oppsummering&&<label className={etikett}>Oppsummering<textarea className={felt} rows={5} value={preview.oppsummering.tekst} onChange={e=>setPreview({...preview,oppsummering:{...preview.oppsummering!,tekst:e.target.value}})}/></label>}{preview.oppgaver.map((o,i)=><label key={o.id} className={etikett}>Spørsmål {o.nummer}<textarea className={felt} value={o.tekst} onChange={e=>setPreview({...preview,oppgaver:preview.oppgaver.map((p,j)=>j===i?{...p,tekst:e.target.value}:p)})}/></label>)}<div className="flex gap-2"><button className={knapp} disabled={venter} onClick={()=>void lagre()}>{venter?"Lagrer…":"Lagre innhold"}</button><button className={sekundar} onClick={()=>setPreview(null)}>Tilbake</button></div></>}{feil}
  </Kort>;
}
function TemaKoblinger({kapittel}:{kapittel:Kapittel}) {
  const {state,appendHendelser}=useStore();const {jobb,feil}=useJobb();const ts=state.temaer.filter(t=>kapittel.temaIds.includes(t.id));
  return <details className="rounded-xl bg-white p-4"><summary className="cursor-pointer text-sm">Temaer og kompetansemål ({ts.length})</summary><p className="my-2 text-xs text-black/55">Koblingen beskriver innholdet. Uttelling krever et selvstendig svar vurdert mot målet.</p>{ts.map(t=><div key={t.id} className="border-t py-2"><p className="text-sm font-medium">{t.navn}</p>{state.kompetansemaal.filter(m=>m.fagId===kapittel.fagId).map(m=><label key={m.id} className="mt-1 flex gap-2 text-xs"><input type="checkbox" checked={t.maalIds.includes(m.id)} onChange={e=>void jobb(async()=>appendHendelser([{...base(nyId("tema-koblet"),kapittel.fagId),type:"tema-koblet",temaId:t.id,maalIds:e.target.checked?[...t.maalIds,m.id]:t.maalIds.filter(id=>id!==m.id),bekreftet:true}]))}/>{m.kortnavn}{t.foreslatteMaalIds?.includes(m.id)?" · AI-forslag":""}</label>)}</div>)}{!ts.length&&<p className="text-sm">Legg til temaer gjennom bokinnleggingen eller AI-chatten.</p>}{feil}</details>;
}
export function ForsokKort({forsok:f}:{forsok:Forsok}) {
  const {state}=useStore();const v=synligVurdering(f,state.hendelser);
  return <article id={`forsok-${f.id}`} className="space-y-2 rounded-xl border border-black/10 bg-white p-4"><p className="text-xs text-black/55">{osloDato(f.tid)} · {MODUS[f.arbeidsmate]} · {HJELP[f.hjelp]}</p><h4 className="text-sm font-medium">{f.sporsmal}</h4><p className="whitespace-pre-wrap text-sm">{f.svar}</p>{v?<div className="space-y-2 border-t pt-3 text-sm"><p className="font-medium">{v.karakter?`Oppgavevurdering: ${v.karakter}/6`:"Tilbakemelding"}</p><p><strong>Dette satt:</strong> {v.riktig||"Ikke spesifisert"}</p><p><strong>Øv på:</strong> {v.mangler||"Ingen mangler registrert"}</p><p><strong>Neste steg:</strong> {v.nesteSteg}</p><p>{v.begrunnelse}</p><p className="text-xs text-black/55">{v.kilde} · {v.modell} · {v.skillId} · {v.kriterieversjon}</p>{v.modellsvar&&<details><summary>Se eksempel på svar</summary><p className="whitespace-pre-wrap">{v.modellsvar}</p></details>}{f.vurderinger.length>1&&<details><summary>Vurderingshistorikk ({f.vurderinger.length})</summary>{f.vurderinger.map(x=><p className="mt-2" key={x.id}>{x.tid}: {x.karakter??"–"} · {x.begrunnelse} · {x.mangler}</p>)}</details>}</div>:<p className="text-sm text-black/60">{f.arbeidsmate==="eksamen"?"Vurdering vises etter at økten avsluttes.":"Svaret er lagret. Venter på vurdering."}</p>}{f.referanser.map((r,i)=><Kilde key={i} refData={r}/>)}</article>;
}
function SvarEditor({oppgave,okt}:{oppgave?:Oppgave;okt?:Okt}) {
  const {state,appendHendelser}=useStore();const [id,setId]=useState(()=>nyId("forsok"));const [svar,setSvar]=useState("");const [sporsmal,setSporsmal]=useState(oppgave?.tekst??okt?.grunnlag??"");const [hjelp,setHjelp]=useState<Hjelp>("ingen");const [modus,setModus]=useState<Arbeidsmate>(okt?.arbeidsmate??"selvtest");const [lagret,setLagret]=useState(false);const {jobb,feil,venter}=useJobb();
  const aktive = foldOkter(state.hendelser).filter(o => o.status === "pagar" && o.fagId === state.innstillinger.aktivtFag && (!oppgave || ((!o.kapittelIds.length || o.kapittelIds.includes(oppgave.kapittelId)) && (!o.oppgaveIds.length || o.oppgaveIds.includes(oppgave.id)))));
  const [valgtOktId,setValgtOktId] = useState("auto");
  const effektivOkt = okt ?? (valgtOktId === "auto" ? aktive.at(-1) : aktive.find(o => o.id === valgtOktId));
  async function lagre(){const f={id,fagId:state.innstillinger.aktivtFag,oktId:effektivOkt?.id,oppgaveId:oppgave?.id,kapittelId:oppgave?.kapittelId,sporsmal,svar,arbeidsmate:effektivOkt?.arbeidsmate??modus,hjelp,referanser:oppgave?.referanse?[oppgave.referanse]:[]};const ok=await jobb(async()=>appendHendelser([{...base(`forsok:${id}`,f.fagId),type:"forsok-lagret",forsok:f}]));if(ok){setSvar("");setId(nyId("forsok"));setLagret(true);}}
  return <div className="space-y-3">{!okt && aktive.length > 0 && <label className={etikett}>Lagre i økt<select className={felt} value={effektivOkt?.id??""} onChange={e=>setValgtOktId(e.target.value)}><option value="">Uten økt</option>{aktive.map(o=><option key={o.id} value={o.id}>{MODUS[o.arbeidsmate]} · {o.grunnlag}</option>)}</select></label>}{!oppgave&&<label className={etikett}>Oppgaven du svarer på<textarea className={felt} value={sporsmal} onChange={e=>setSporsmal(e.target.value)}/></label>}{!effektivOkt&&<label className={etikett}>Arbeidsmåte<select className={felt} value={modus} onChange={e=>setModus(e.target.value as Arbeidsmate)}><option value="laering">Læring</option><option value="selvtest">Selvtest</option></select></label>}<label className={etikett}>Ditt svar<textarea className={`${felt} min-h-40`} value={svar} onChange={e=>{setSvar(e.target.value);setLagret(false);}}/></label><label className={etikett}>Hjelp brukt<select className={felt} value={hjelp} onChange={e=>setHjelp(e.target.value as Hjelp)}>{Object.entries(HJELP).map(([id,navn])=><option value={id} key={id}>{navn}</option>)}</select></label><button className={knapp} disabled={venter||!svar.trim()} onClick={()=>void lagre()}>{venter?"Lagrer…":"Lagre besvarelse"}</button>{lagret&&<p role="status" className="text-sm text-green-800">Besvarelsen er lagret.</p>}{feil}</div>;
}
function OppgaveKort({oppgave:o}:{oppgave:Oppgave}) {
  const {state,appendHendelser}=useStore();const [svarer,setSvar]=useState(false);const {jobb,feil}=useJobb();const k=state.kapitler.find(k=>k.id===o.kapittelId)!;
  const fs=foldForsok(state.hendelser).filter(f=>f.oppgaveId===o.id);
  return <Kort><h4 className="text-sm font-medium">{o.nummer?`${o.nummer.replace(/[.)]+$/, "")}. `:""}{o.tekst}</h4><p className="text-xs text-black/55">{o.opphav==="ai"?"AI-variant av bokoppgave":"Bokoppgave"} · {fs.length} forsøk{o.koblingBekreftet?" · Kobling bekreftet":" · Kobling ikke bekreftet"}</p><Kilde refData={o.referanse}/><button className={sekundar} onClick={()=>setSvar(!svarer)}>{svarer?"Lukk svarfelt":"Svar på oppgaven"}</button>{svarer&&<SvarEditor oppgave={o}/>}
    <details><summary className="text-sm">Knytt til underpunkt, tema og mål</summary><label className={etikett}>Underpunkt<select className={felt} value={o.underpunktId??""} onChange={e=>void jobb(async()=>appendHendelser([{...base(nyId("oppgave-koblet"),k.fagId),type:"oppgave-koblet",oppgaveId:o.id,underpunktId:e.target.value||null,temaIds:o.temaIds,maalIds:o.maalIds,bekreftet:o.koblingBekreftet}]))}><option value="">Hele kapittelet</option>{underpunkter(k).map(s=><option key={s.id} value={s.id}>{s.navn}</option>)}</select></label>{o.underpunktId&&<p className="text-xs">{underpunkter(k).find(s=>s.id===o.underpunktId)?.navn}</p>}{state.temaer.filter(t=>k.temaIds.includes(t.id)).map(t=><label key={t.id} className="mt-2 flex gap-2 text-xs"><input type="checkbox" checked={o.temaIds.includes(t.id)} onChange={e=>void jobb(async()=>appendHendelser([{...base(nyId("oppgave-koblet"),k.fagId),type:"oppgave-koblet",oppgaveId:o.id,temaIds:e.target.checked?[...o.temaIds,t.id]:o.temaIds.filter(id=>id!==t.id),maalIds:o.maalIds,bekreftet:true}]))}/>{t.navn}</label>)}{state.kompetansemaal.filter(m=>m.fagId===k.fagId).map(m=><label key={m.id} className="mt-1 flex gap-2 text-xs"><input type="checkbox" checked={o.maalIds.includes(m.id)} onChange={e=>void jobb(async()=>appendHendelser([{...base(nyId("oppgave-koblet"),k.fagId),type:"oppgave-koblet",oppgaveId:o.id,temaIds:o.temaIds,maalIds:e.target.checked?[...o.maalIds,m.id]:o.maalIds.filter(id=>id!==m.id),bekreftet:true}]))}/>{m.kortnavn}</label>)}{feil}</details>
    {fs.length>0&&<details><summary className="text-sm">Besvarelser og tilbakemeldinger</summary><div className="mt-3 space-y-3">{fs.slice().reverse().map(f=><ForsokKort key={f.id} forsok={f}/>)}</div></details>}
  </Kort>;
}
function Hull({kapittel}:{kapittel:Kapittel}) {
  const {state}=useStore();const ko=ovingKo(state,kapittel.fagId,{kapittelId:kapittel.id,repetisjon:true});const fs=foldForsok(state.hendelser).filter(f=>f.kapittelId===kapittel.id&&synligVurdering(f,state.hendelser)?.mangler);
  return <><Kort><h3 className="font-medium">Dette må jeg øve på</h3>{ko.map(r=><p key={r.oppgave.id} className="text-sm"><strong>{r.grunn}:</strong> {r.oppgave.tekst}</p>)}{!ko.length&&<p className="text-sm">Ingen oppgaver i repetisjonskøen akkurat nå.</p>}<OktStart kapittel={kapittel}/></Kort>{fs.slice().reverse().map(f=><ForsokKort key={f.id} forsok={f}/>)}</>;
}
function VedleggKort({v}:{v:KapittelVedlegg}) {
  const [url,setUrl]=useState("");const [feil,setFeil]=useState("");
  useEffect(()=>{let aktiv=true;const hent=()=>void vedleggUrl(v).then(url=>{if(aktiv){setUrl(url);setFeil("");}}).catch(e=>{if(aktiv)setFeil(String(e));});hent();const timer=window.setInterval(hent,240000);return()=>{aktiv=false;window.clearInterval(timer);};},[v]);
  return <div className="space-y-2 rounded-xl border p-3"><p className="text-sm font-medium">{v.filnavn}</p>{url&&(v.mime==="application/pdf"?<iframe title={v.filnavn} src={url} className="h-80 w-full"/>:v.mime!=="image/heic"?<img alt={v.filnavn} src={url} className="max-h-72 object-contain"/>:null)}{url&&<a href={url} target="_blank" rel="noreferrer" className="text-sm underline">Åpne eller last ned original</a>}{feil&&<p role="alert" className="text-sm text-red-800">{feil}</p>}</div>;
}
function Vedlegg({kapittel}:{kapittel:Kapittel}) {
  const {state,innlogget,appendHendelser}=useStore();const {jobb,venter,feil}=useJobb();const vs=state.hendelser.filter((h):h is KapittelVedlegg=>h.type==="kapittel-vedlegg"&&h.kapittelId===kapittel.id);
  return <Kort><h3 className="font-medium">Foto og PDF</h3><p className="text-sm text-black/60">Last opp originalen her. Be AI-en hente og lese vedlegget. Hvis chatten ikke støtter dette: last ned filen og legg den ved i chatten.</p><label className={etikett}>Last opp fil<input className={felt} type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/heic,application/pdf,.heic" disabled={venter} onChange={e=>{const f=e.target.files?.[0];if(f)void jobb(()=>lastOppVedlegg(f,kapittel.fagId,kapittel.id,!!innlogget,appendHendelser));e.target.value="";}}/></label><p className="text-xs text-black/50">Foto maks 12 MB · PDF maks 25 MB</p>{feil}{vs.map(v=><VedleggKort key={v.vedleggId} v={v}/>)}</Kort>;
}
export function OktStart({kapittel}:{kapittel?:Kapittel}) {
  const {state,appendHendelser}=useStore();const fagId=state.innstillinger.aktivtFag;const [id,setId]=useState(()=>nyId("okt"));const [modus,setModus]=useState<Arbeidsmate>("selvtest");const [grunnlag,setGrunnlag]=useState(kapittel?`Øving i kapittel ${kapittel.nummer}: ${kapittel.navn}`:"");const [minutter,setMinutter]=useState("");const [hjelpemidler,setHjelpemidler]=useState("Ingen oppgitt");const [laget,setLaget]=useState<Okt|null>(null);const {jobb,feil,venter}=useJobb();
  async function start(){const o={id,fagId,arbeidsmate:modus,kapittelIds:kapittel?[kapittel.id]:[],oppgaveIds:kapittel?oppgaver(state,kapittel.id).map(o=>o.id):[],grunnlag,hjelpemidler,...(minutter?{minutter:Number(minutter)}:{})};const h:Hendelse={...base(`okt:${id}`,fagId),type:"okt-startet",okt:o};const ok=await jobb(async()=>appendHendelser([h]));if(ok){setLaget({...o,tid:h.tid,status:"pagar"});setId(nyId("okt"));}}
  return <div className="space-y-3 rounded-xl bg-[#F6F5F1] p-4"><h3 className="font-medium">Start økt{kapittel?` · kapittel ${kapittel.nummer}`:" på tvers av kapitler"}</h3><label className={etikett}>Arbeidsmåte<select className={felt} value={modus} onChange={e=>setModus(e.target.value as Arbeidsmate)}>{Object.entries(MODUS).map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></label>{modus==="eksamen"&&<p className="text-sm">{EKSAMEN[fagId as keyof typeof EKSAMEN]?.form} · samlet vurdering etter økten.</p>}<label className={etikett}>Oppgavegrunnlag<textarea className={felt} value={grunnlag} onChange={e=>setGrunnlag(e.target.value)} placeholder="Hva vil du arbeide med? Lim inn en case eller oppgavetekst."/></label><div className="grid gap-3 sm:grid-cols-2"><label className={etikett}>Hjelpemidler<input className={felt} value={hjelpemidler} onChange={e=>setHjelpemidler(e.target.value)}/></label><label className={etikett}>Tidsramme i minutter (valgfri)<input className={felt} type="number" min="1" value={minutter} onChange={e=>setMinutter(e.target.value)} placeholder="Uten tidsgrense"/></label></div><button className={knapp} disabled={venter||!grunnlag.trim()} onClick={()=>void start()}>{venter?"Lagrer…":"Opprett økt"}</button>{feil}{laget&&<KopierAi okt={laget}/>}</div>;
}
export function OvingRom() {
  const {state,appendHendelser,appendHoring}=useStore();const fagId=state.innstillinger.aktivtFag;const [visAntall,setAntall]=useState(20);const [valgt,setValgt]=useState<string|null>(null);const {jobb,feil}=useJobb();
  const os=foldOkter(state.hendelser).filter(o=>o.fagId===fagId).reverse();const aktiv=os.find(o=>o.id===valgt);const fs=foldForsok(state.hendelser).filter(f=>f.fagId===fagId).reverse();
  return <div className="space-y-5"><OktStart/><Kort><h3 className="font-medium">Dine økter</h3>{os.length?os.map(o=><button key={o.id} className={`block w-full rounded-lg p-3 text-left text-sm ${aktiv?.id===o.id?"bg-[#E6EFE8]":"bg-[#F6F5F1]"}`} onClick={()=>setValgt(o.id)}>{MODUS[o.arbeidsmate]} · {o.status==="pagar"?"Pågår":o.status==="fullfort"?"Fullført":"Avbrutt"} · {osloDato(o.tid)}<span className="mt-1 block text-black/60">{o.grunnlag}</span></button>):<p className="text-sm text-black/55">Start en økt her eller fra boka.</p>}</Kort>
    {aktiv&&<Kort><h3 className="font-medium">{MODUS[aktiv.arbeidsmate]} · {EKSAMEN[fagId as keyof typeof EKSAMEN]?.form}</h3><p className="whitespace-pre-wrap text-sm">{aktiv.grunnlag}</p><p className="text-xs text-black/55">{aktiv.minutter?`${aktiv.minutter} minutter fra ${new Date(aktiv.tid).toLocaleTimeString("nb-NO")}`:"Uten tidsgrense"} · Hjelpemidler: {aktiv.hjelpemidler}</p>
      {aktiv.status==="pagar"?<><KopierAi okt={aktiv}/><SvarEditor key={aktiv.id} okt={aktiv}/><div className="flex gap-2">{aktiv.arbeidsmate!=="eksamen"&&<button className={sekundar} onClick={()=>void jobb(async()=>appendHendelser([{...base(`slutt:${aktiv.id}`,fagId),type:"okt-avsluttet",oktId:aktiv.id,status:"fullfort"}]))}>Fullfør økt</button>}<button className={sekundar} onClick={()=>void jobb(async()=>appendHendelser([{...base(`slutt:${aktiv.id}`,fagId),type:"okt-avsluttet",oktId:aktiv.id,status:"avbrutt"}]))}>Avbryt økt</button></div>{aktiv.arbeidsmate==="eksamen"&&<p className="text-sm text-black/55">Be AI-en gi samlet vurdering og avslutte økten.</p>}</>:aktiv.vurdering?<div className="space-y-2 text-sm"><h4 className="font-medium">Samlet øktvurdering{aktiv.vurdering.karakter?`: ${aktiv.vurdering.karakter}/6`:""}</h4><p>{aktiv.vurdering.begrunnelse}</p><p>Mangler belegg: {aktiv.vurdering.manglerBelegg||"Ingen oppgitt"}</p><p className="text-xs text-black/55">{aktiv.vurdering.modell} · {aktiv.vurdering.kriterieversjon}</p></div>:null}{feil}{fs.filter(f=>f.oktId===aktiv.id).map(f=><ForsokKort key={f.id} forsok={f}/>)}</Kort>}
    <section className="space-y-3"><h3 className="font-medium">Besvarelser og vurderinger</h3>{fs.slice(0,visAntall).map(f=><ForsokKort key={f.id} forsok={f}/>)}{fs.length>visAntall&&<button className={sekundar} onClick={()=>setAntall(visAntall+20)}>Vis flere</button>}</section>
    <details><summary className="text-sm">Eldre høringer · hjelp og vurderingsgrunnlag kan være ukjent</summary><div className="mt-3"><Prover state={{...state,horinger:state.horinger.filter(h=>!h.forsokId)}} onLagreHoring={h=>void appendHoring(h).catch(()=>undefined)} prompts={state.prompts}/></div></details>
  </div>;
}
export function FramgangRom() {
  const {state,appendHendelser}=useStore();const fagId=state.innstillinger.aktivtFag;const f=framgang(state,fagId);const {jobb,feil}=useJobb();const ko=ovingKo(state,fagId,{repetisjon:true});
  return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3">{[["Arbeid gjennomført",`${f.forsok} besvarelser`],["Selvstendig vist",`${f.selvstendige} vurderte svar`],["Repetisjon",`${ko.length} aktuelle oppgaver`]].map(([t,v])=><Kort key={t}><p className="text-sm text-black/55">{t}</p><p className="text-xl font-medium">{v}</p></Kort>)}</div><Kort><h3 className="font-medium">Ukesmål · {f.denneUken} av {f.ukesmaal} økter</h3><progress className="w-full accent-[#2E6B4B]" max={f.ukesmaal} value={f.denneUken}/><label className={etikett}>Økter per uke<input className={felt} type="number" min="1" max="50" defaultValue={f.ukesmaal} onBlur={e=>{const antall=Number(e.target.value);if(antall!==f.ukesmaal)void jobb(async()=>appendHendelser([{...base(nyId("ukesmaal"),fagId),type:"ukesmaal-satt",antall}]));}}/></label><p className="text-xs text-black/55">Uken følger norsk tid. Aktivitet og karakter vurderes separat.</p>{feil}</Kort><Kort><h3 className="font-medium">Milepæler</h3>{f.milepaeler.length?f.milepaeler.map(m=><p className="text-sm" key={m}>✓ {m}</p>):<p className="text-sm text-black/55">Din første selvstendige vurdering blir den første milepælen.</p>}</Kort><p className="text-sm text-black/55">Grafen under viser oppgavevurderinger og historiske høringer, ikke forventet eksamenskarakter.</p><Utvikling state={state}/></div>;
}
